#!/bin/sh
ssh ubuntu@106.10.38.126 -p 18082 <<EOF
    cd ~/api-test		
    git pull origin main
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 16.4.0
    npm install
    npm install -g typescript
    npm install -g ts-node
    npm install -g pm2
    pm2 install typescript
    pm2 restart ecosystem.config.js
    exit
EOF
